add actors_model_example
euranova/code_retreat pull request #38
Opened 2021-03-22 16:31 UTC by azimgivron

Let me know if there are changes to make. 
The code is the same as in the normal scaffold/python with the src/my_module.py that was updated. 
However, I only added the '&& pip install thespian==3.10.3' in the Dockerfile but it does not seem to be rebuilt when running the build script. Can you tell me what I should add to solve this ?

2021-03-23 14:42 UTC, jbruggem requested changes
Great start !

Two things:
- some clean up to do.
- it missing an example of how to get an actor's address based on its name. Is that possible with thespian ?

thanks for your contribution !

2021-03-23 14:42 UTC, jbruggem commented on scaffolds_actor_model/python/python-env
> +  $TAG $@
Nit-picking: there's a new line missing at the end of the file

2021-03-23 14:42 UTC, jbruggem commented on scaffolds_actor_model/python/src/my_module.py
> +     actor_sys.tell(actor1, {"msg_type": "send_msg", "content": "hello world"})
nit-picking: missing empty line at EOF

2021-03-23 14:42 UTC, jbruggem commented on scaffolds_actor_model/python/src/my_module.py
> +               self.neighbour = msg["address"]
The use of *neighbour* makes me think that you had a particular use case (our experiment with a concurrent GoL), but this example should be use-case agnostic. Maybe renaming the variable is enough ?

WDYT ?

2021-03-23 14:42 UTC, jbruggem commented on scaffolds_actor_model/python/src/test/test_my_module.py
> +from my_module import GameOfLife
This example should be agnostic, so shouldn't mention any particular use case.

Besides, I don't see any `GameOfLife` in `my_module`.

Could you make sure that references to GoL are removed, and that the tests of the scaffold pass (there should only be one or two, as an example of how to write tests)

2021-03-24 08:26 UTC, azimgivron commented
> Great start !
> 
> Two things:
> 
> * some clean up to do.
> * it missing an example of how to get an actor's address based on its name. Is that possible with thespian ?
> 
> thanks for your contribution !

I made the requested changes, let me know if there is something else to modify. 
The reason I left the address passing in as initialization message is because to get the actors by name, you need to call the actor system and I am wondering whether it is not a bottleneck since it needs to be centralized. However, both options are in the example.

2021-03-25 09:50 UTC, merged